[backup] fixed several bugs in the backup script, see http://knowledgeforge.net/okfn/tasks/ticket/624

diff --git a/etc/backup/backup.d/10mysql b/etc/backup/backup.d/10mysql
--- a/etc/backup/backup.d/10mysql
+++ b/etc/backup/backup.d/10mysql
@@ -1,9 +1,15 @@
-#!/bin/bash
+if ! [ -z ${DB_DUMP_DIR} ] ; then
+    OUTPUT=${DB_DUMP_DIR}/mysqldump.sql
+    MYSQL_OPTIONS="--opt --all-databases"
 
-. /etc/backup/backup.d/common
+    if ! [ -z ${MYSQL_PASSWORD} ] ; then
+      MYSQL_OPTIONS="${MYSQL_OPTIONS} --password=${MYSQL_PASSWORD}"
+    fi
 
-OUTPUT=${DB_DUMP_DIR}/mysqldump.sql
-
-mkdir -p ${DB_DUMP_DIR}
-rm -f -- ${OUTPUT}
-mysqldump --opt --all > ${OUTPUT}
+    ${MKDIR} -p ${DB_DUMP_DIR}
+    ${RM} -f -- ${OUTPUT}{,.gz} 
+    /usr/bin/mysqldump ${MYSQL_OPTIONS} > ${OUTPUT}
+    /bin/gzip ${OUTPUT}
+else
+    echo "ERROR: DB_DUMP_DIR not set, cannot dump mysql" 1>&2
+fi
diff --git a/etc/backup/backup.d/15postgres b/etc/backup/backup.d/15postgres
--- a/etc/backup/backup.d/15postgres
+++ b/etc/backup/backup.d/15postgres
@@ -1,9 +1,10 @@
-#!/bin/bash
+if ! [ -z ${DB_DUMP_DIR} ] ; then
+    OUTPUT=${DB_DUMP_DIR}/pgdump.sql
 
-. /etc/backup/backup.d/common
-
-OUTPUT=${DB_DUMP_DIR}/pgdump.sql
-
-mkdir -p ${DB_DUMP_DIR}
-rm -f -- ${OUTPUT}
-su postgres -c pg_dumpall > ${OUTPUT}
+    ${MKDIR} -p ${DB_DUMP_DIR}
+    ${RM} -f -- ${OUTPUT}{,.gz}
+    /usr/bin/sudo -u postgres /usr/bin/pg_dumpall > ${OUTPUT}
+    /bin/gzip ${OUTPUT}
+else
+    echo "ERROR: DB_DUMP_DIR not set, cannot dump postgres" 1>&2
+fi
