[backup] Added proper locking to simple rsync pull

diff --git a/etc/backup/rsync-pull-simple-backup-to-s058 b/etc/backup/rsync-pull-simple-backup-to-s058
--- a/etc/backup/rsync-pull-simple-backup-to-s058
+++ b/etc/backup/rsync-pull-simple-backup-to-s058
@@ -17,6 +17,22 @@ LANDING_ZONE="/home/backup/rsync-landingzones"
 RSYNC="/usr/bin/rsync"
 RSYNC_OPTIONS="--rsh=ssh --archive --sparse --compress"
 
+NAME=$(basename $0)
+PID_FILE=/var/run/${NAME}.pid
+LOG_TAG="[${NAME}]"
+
+
+if [ -f ${PID_FILE} ] ; then
+    PID=`cat ${PID_FILE}`
+    if [ -d /proc/${PID} ] ; then
+        echo "ERROR: This job '${NAME}' is already running with pid ${PID}! Exiting." 1>&2
+        exit 1
+    fi
+    echo "WARNING: removing stale pid file ${PID_FILE}" 1>&2
+    rm ${PID_FILE}
+fi 
+echo $$  >  ${PID_FILE}
+sleep 10
 
 for source in ${SOURCES} ; do
     target="${LANDING_ZONE}/`echo ${source} | sed -e s,:,,`"
@@ -24,3 +40,4 @@ for source in ${SOURCES} ; do
     ${RSYNC} ${RSYNC_OPTIONS} ${source} ${target}
 done
 
+rm ${PID_FILE}
